import { toolImpls } from "./tools";
import type { ToolName } from "./schemas";

type ImplFn = (input: Record<string, unknown>) => Promise<unknown>;

export const toolImplMap: Record<ToolName, ImplFn> = {
  list_projects: () => toolImpls.listProjects(),
  list_areas: () => toolImpls.listAreas(),
  get_context: toolImpls.getContext as ImplFn,
  create_project: toolImpls.createProject as ImplFn,
  create_area: toolImpls.createArea as ImplFn,
  create_task: toolImpls.createTask as ImplFn,
  update_task: toolImpls.updateTask as ImplFn,
  decompose_task: toolImpls.decomposeTask as ImplFn,
  move_to_parking_lot: toolImpls.moveToParkingLot as ImplFn,
  add_journal: toolImpls.addJournal as ImplFn,
  list_events: toolImpls.listEvents as ImplFn,
  create_event: toolImpls.createEvent as ImplFn,
  update_event: toolImpls.updateEvent as ImplFn,
  get_daily: () => toolImpls.getDaily(),
  log_daily: toolImpls.logDaily as ImplFn,
  create_habit: toolImpls.createHabit as ImplFn,
  create_rhythm: toolImpls.createRhythm as ImplFn,
  create_meal: toolImpls.createMeal as ImplFn,
  add_grocery: toolImpls.addGrocery as ImplFn,
  set_grocery: toolImpls.setGrocery as ImplFn,
  search_knowledge: toolImpls.searchKnowledge as ImplFn,
  read_note: toolImpls.readNote as ImplFn,
  read_task_detail: toolImpls.readTaskDetail as ImplFn,
  write_task_detail: toolImpls.writeTaskDetail as ImplFn,
  read_task_comments: toolImpls.readTaskComments as ImplFn,
  add_task_comment: toolImpls.addTaskComment as ImplFn,
  add_note: toolImpls.addNote as ImplFn,
  update_note: toolImpls.updateNote as ImplFn,
  attach_image: toolImpls.attachImage as ImplFn,
  next_actions: () => toolImpls.nextActions(),
  list_targets: (a) => toolImpls.listTargets(a as { project?: string }),
  list_components: (a) => toolImpls.listComponents(a as { project: string }),
  weekly_summary: () => toolImpls.weeklySummary(),
  life_trends: () => toolImpls.lifeTrends(),
  propose_changes: toolImpls.proposeChanges as ImplFn,
};
